[package]
name = "miniquad"
version = "0.1.0"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2018"

[dependencies]
sokol_app_sys = { path = "./sokol-app-sys", version = "0.1.0" }

[dev-dependencies]
glam = {version = "0.8", features = ["scalar-math"] }